---
- hosts: webservers
  become: true
  vars:
  - warName: demo-0.0.1-SNAPSHOT.war
  - warRemotePath: /var/www/html

  tasks:
  - name: Download WAR to server
    command: wget target/{{ warName }} -O {{ warRemotePath }}/{{ warName }}
    notify:
        - restart apache2
   
    
  - name: wait for apache2 to start
    wait_for: port=8080 timeout=60
    
  handlers:
    - name: Restart apache2
      service: name=apache2 state=restarted
